# /etc/apache2/sites-available/ati_app.conf

<VirtualHost *:80>
    ServerName localhost
    ServerAdmin webmaster@localhost

    # DocumentRoot puede ser genérico, ya que Flask manejará las peticiones /ATI/.
    # Apúntalo a un directorio que no contendrá los archivos de tu aplicación
    # para evitar listados de directorio o conflictos no deseados.
    DocumentRoot /var/www/html/ 

    RedirectMatch ^/$ /ATI/


    WSGIDaemonProcess myapp python-home=/opt/web_cache_pty_app/web_cache_pty_env user=www-data group=www-data processes=2 threads=15

    # ESTA ES LA ÚNICA DIRECTIVA DE WSGI SCRIPT ALIAS NECESARIA PARA /ATI/
    # WSGIScriptAlias /ATI apunta a la raíz de tu aplicación Flask (app.py).
    # Flask, a través de sus rutas (@app.route('/'), @app.route('/<path:filename>')),
    # servirá index.html, perfil.html, css, js, y todas las imágenes.
    WSGIScriptAlias /ATI /opt/web_cache_pty_app/ATI/app.py process-group=myapp application-group=%{GLOBAL}

    # Configuración para el directorio de tu aplicación WSGI en el sistema de archivos.
    # Aquí está el código Python y el entorno virtual.
    <Directory /opt/web_cache_pty_app/ATI/>
        # Deshabilitar MultiViews e Indexes para evitar listados de directorio
        # o intentos de servir archivos incorrectos por Apache en lugar de Flask.
        Options +FollowSymLinks -MultiViews -Indexes 
        Require all granted 
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
